calebdwilliams/element-internals-polyfill

- README.md
Hi @calebdwilliams, thanks for the polyfill. The name in README seems to be a leftover from the other one.
> Update npm package name in README

- src/element-internals.js
This PR will change where MutationObserver will watch from `<body>` to `<html>`.
The current script didn't work when `<script src="element-internal-polyfill.js"></script>` is put in `<head>` since the script refers to `document.body` but `body` is not populated yet when a script loaded is loaded in `<head>`. It works if the script tag is put inside <body>, but I think not depending on `document.body` would make this polyfill more useful.
> observe document element so that the script can be put in <head>

- src/utils.ts
This PR removes `console.log()` which I believe in there unintentionally.
> remove console.log()

- src/element-internals.ts
- src/utils.ts
- test/ElementInternals.test.js
I found that `this.internals` in available when `formAssociatedCallback` is called in the Chrome implementation but not in the polyfill implementation. This fix makes sure to call `formAssociatedCallback` in a later event loop cycle to fix that issue.
> fix(formAssociatedCallback): make sure internals are available when formAssociatedCallback is called

- src/element-internals.ts
- src/maps.ts
- src/mutation-observers.ts
- src/types.ts
- src/utils.ts
- test/ElementInternals.test.js
This PR adds support for passing FormData to setFormValue to allow setting multiple form values as supported in the Chrome implementation. Not sure if you had something else in mind already considering https://github.com/calebdwilliams/element-internals-polyfill/issues/17 but I thought I'd share anyway if you're interested in merging this.
Edit: I think this also closes #18 
Edit 2: Closes #20
> setFormValue: Adds support for FormData

- src/element-internals.ts
- test/ElementInternals.test.js
Found an inconsistency with Chrome. Chrome accepts empty strings in `setFormValue` the polyfill does not.
> fix(setFormValue): accept empty strings like Chrome

- src/element-internals.ts
- test/ElementInternals.test.js
Another Chrome inconsistency. Chrome allows you to call `setValidity` with a `ValidityState` from a native input, this fails in the polyfill.
I found that `Object.keys()` always returns an empty array when passed a `ValidityState` object and spread syntax (...) does not work either. Iterating with `for...in` works though, so I added a step to ensure the input is an object to make sure `Object.keys()` and `...` works as expected.
> fix(setValidity): Added support for setting ValidityState from a native input as Chrome

- src/utils.ts
- test/ElementInternals.test.js
I noticed that the focus order was in reverse compared to Chrome when submitting forms with invalid inputs. This PR corrects that issue.
> fix: anchor element focus order on form submission reversed compared to Chrome

- CHANGELOG.md
- package-lock.json
- package.json
- src/element-internals.ts
- src/types.ts
- src/utils.ts
Lit-element rendering has issue with setting element before it does it's first update.  You can see this best when creating a custom element that uses a select element underneath.  Options for the select are rendered in plain text a few elements because the custom element.
This is framework specific so I don't know if this is something you would like in this polyfill.
> fix: add hidden input for lit-element after render completes

- src/types.ts
I found a small issue in the typedefs :
```
../../node_modules/element-internals-polyfill/dist/element-internals.d.ts:61:9 - error TS2416: Property 'shadowRoot' in type 'ElementInternals' is not assignable to the same property in base type 'IElementInternals'.
Type 'ShadowRoot | null' is not assignable to type 'ShadowRoot'.
Type 'null' is not assignable to type 'ShadowRoot'.
```
This PR fix this
> fix: add missing null to shadowRoot

- src/utils.ts
- test/ElementInternals.test.js
I found that Chrome does not search past closed shadow roots for the form element. This made the polyfill inconsistent with the Chrome implementation. Running the test without the fix should confirm it. I wasn't able to run the tests on Safari so if someone else can do that to confirm it works it would be super.
> Form discovery inconsistency

- src/mutation-observers.ts
This PR is an improvement for the fix for issue #73 
FILTER_REJECT rejects nodes that might have children
of type form-associated custom elements. Instead, use FILTER_SKIP.
This option traverses the children in such cases.
> Fix: fix nodes added in a tree in Safari

- src/maps.ts
- src/utils.ts
Listen for submit events on the closest submit button and if the form is invalid prevent the default handling.
For more information see this [explanation](https://github.com/calebdwilliams/element-internals-polyfill/issues/40#issuecomment-1244024843).
> Fix issue #40.

- src/mutation-observers.ts
I found this condition making my tests in jest fail when the third statement was evaluated. This fixes it.
> fix: fixes condition in mutation observer

- src/utils.ts
This fixes the differences in disabled behaviour between `initRef` and the mutation observer callback.
> Fix differences in disabled behavior

- src/utils.ts
reverse the order of the check so that if the control is NOT a native control it doesnt have to have a validity object established when this setFormValidity function runs. It could run in the constructor and not have validity or attributes yet because of the microtask etc.
> fix(utils): flip order of nativeControlValidity filter predicate check

- src/CustomStateSet.ts
- test/CustomStateSet.test.ts
do the same setTimeout approach for delete states also.
I traced my tests and figured out that it was the delete case causing my errors. Adding this exact logic locally passes my tests in jest/jsdom with element internals and react/react testing library `createElement` calls
> fix: custom states will delay if removed in constructor

- src/element-internals.ts
- src/utils.ts
would love your input on the `upgradeInternals` change and how/whether or not to use `deferUpgrade()` there instead.
The issue is that in react/jest/jsdom, each FACE needs a polyfilled internals because jsom doesn't support `attachInternals()`. Since react renders in a depth-first approach, each FACE is constructed basically standalone. Therefore, the `findParentForm()` feature of the `upgradeInternals()` process will return null and the form's initial validity won't be correct because not all the child FACE's will be registered in the internal elements map used for validity.
> Running implementation refactors for jest/jsdom environment

- src/utils.ts
Hi there,
Great work in the polyfill. Thank you :)
The polyfill throws an error in Safari 13 when clicking in a form, due to `:is` selector not being supported.
This PR selects the same elements but without using `:is`.
Working example: [https://jsitor.com/dAkiiSwGBO](https://jsitor.com/dAkiiSwGBO)
Related to #82 and #40 
Thanks!
> fix: remove :is in submit selector to prevent error in non-supporting browsers

- src/mutation-observers.ts
- test/ElementInternals.test.js
I found this bug while developing some components, and relying in element internals for setting aria attributes.
If you place a non form associated element inside of a form, the polyfill treats it as a form associated element and that fails.
> fix: only inits form association if element is form associated

- src/element-internals.ts
- src/index.ts
- src/mutation-observers.ts
We expose the `forceCustomStateSetPolyfill()` and `forceElementInternalsPolyfill()` functions as well as make the polyfill not **exception** when the Custom Elements and or the Shady DOM Polyfill is also applied. **NOTE:** with these polyfills, the EI polyfill will not work as intended, but it enables custom elements using ElementInternals from exceptioning in these cases.
The main use case for this is for consuming WCs that use ElementInternals Chrome extensions. Content Scripts in Chrome extensions (until we have scoped custom elements) require you use the CE polyfill. WCs that have ElementInternals will exception because they are being applied to non-custom elements. This polyfill will not help because it does feature detection and chrome has EI. Therefore we need EI polyfill to be …
> Expose functions to force the polyfill and make not exception with WC polyfill

- src/aom.ts
- src/element-internals.ts
- src/types.ts
Fixes #128 
Supports change to TypeScript's generated DOM `ARIAMixin` interface in TS 5.4.
> Add ariaDescription to interfaces

- src/aom.ts
- src/element-internals.ts
- src/mutation-observers.ts
- src/utils.ts
Polyfill works differently than native implementation because it is limited by browser capabilities. Specifically polyfill lacks special interaction of `ElementInternals` with a11y tools (like screen readers).
Native `ElementInternals` reports validity status to screen readers without using aria-* attributes (specifically `aria-invalid`).
In comparison to other attribute modification methods (`removeAttribute` and `toggleAttribute`), `setAttribute` always triggers `attributeChangedCallback` even if the actual value has not changed.
In my code I call `setValidity` from attribute changed callback. My component's validation relies on attributes, so when they have changed it makes sense to revalidate it.
Simplifying I can illustrate the problem with the following code:
```
class MyComponent …
```
> Fix attributeChangedCallback when calling setValidity

- package-lock.json
- package.json
- src/element-internals.ts
- src/mutation-observers.ts
- src/utils.ts
- test/CustomStateSet.test.ts
- test/FormElements.test.ts
Due to inactivity on #130 that fixes #127, which we need in our project, I forked the original PR and implemented the requested changes, hopefully so that it can get merged soon.
To address @calebdwilliams [comment ](https://github.com/calebdwilliams/element-internals-polyfill/pull/130/files#r1777918654) regarding removing the guard against a second instance, this didn't work out for us, as we need the upgradeInternals to be called. I therefore added a flag to prevent the error being thrown if the attach internals function is run in upgradeInternals.
I also fixed some rollup warnings, like circular dependencies, undefined this, and missing name argument. 
All credits to @christophe-g for the original implementation. I mean no disrespect by implementing his change, and would be more than …
> Updated: "Fix element not calling attach internals"
